version: '3'

services:
  producer1:
    build:
      context: ./producer1
      no_cache: true
    env_file:
      - ./MSize.env
    networks:
      - lab2network
    cpu_quota: 200000
    cpu_period: 100000
    mem_limit: 1g

  producer2:
    build:
      context: ./producer2
      no_cache: true
    env_file:
      - ./MSize.env
    networks:
      - lab2network
    cpu_quota: 200000
    cpu_period: 100000
    mem_limit: 1g

  consumer:
    build:
      context: ./consumer
      no_cache: true
    networks:
      - lab2network
    cpu_quota: 300000
    cpu_period: 100000
    mem_limit: 2g
#    deploy:
#      replicas: 3  # Увеличиваем количество реплик для горизонтального масштабирования

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключаем нашу конфигурацию
    networks:
      - lab2network
    ports:
      - "80:80"  # Открываем порт для входящих запросов
    depends_on:
      - consumer
      - producer1
      - producer2

networks:
  lab2network:
    driver: bridge
